# Generated by Django 5.0.4 on 2025-05-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_blog_juizuser_recipe_tutorial_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/all'),
        ),
    ]
